/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import View.JDlgAfbFornecedores;

/**
 *
 * @author u07994189199
 */
public class JFrmAfbPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmAfbPrincipal
     */
    public JFrmAfbPrincipal() {
        initComponents();
        setTitle("Tela Principal");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMnuAfbUsuario = new javax.swing.JMenuItem();
        jMnuAfbClientes = new javax.swing.JMenuItem();
        jMnuAfbFornecedores = new javax.swing.JMenuItem();
        jMnuAfbProdutos = new javax.swing.JMenuItem();
        jMnuAfbVendedores = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuAfbSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Cadastro");

        jMnuAfbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuAfbUsuario.setText("Usuario");
        jMnuAfbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAfbUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuAfbUsuario);

        jMnuAfbClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuAfbClientes.setText("Clientes");
        jMnuAfbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAfbClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuAfbClientes);

        jMnuAfbFornecedores.setText("Fornecedores");
        jMnuAfbFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAfbFornecedoresActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuAfbFornecedores);

        jMnuAfbProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuAfbProdutos.setText("Produtos");
        jMenu2.add(jMnuAfbProdutos);

        jMnuAfbVendedores.setText("Vendedores");
        jMenu2.add(jMnuAfbVendedores);
        jMenu2.add(jSeparator1);

        jMnuAfbSair.setText("Sair");
        jMenu2.add(jMnuAfbSair);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Movimento");

        jMenuItem9.setText("Venda");
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("Venda_Produto");
        jMenu1.add(jMenuItem10);

        jMenuItem7.setText("Compra");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Compra_Produto");
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuAfbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAfbUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgAfbUsuarios jDlgAfbUsuarios = new JDlgAfbUsuarios(null, true);
        jDlgAfbUsuarios.setVisible(true);
        
    }//GEN-LAST:event_jMnuAfbUsuarioActionPerformed

    private void jMnuAfbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAfbClientesActionPerformed
       JDlgAfbClientes jDlgAfbClientes = new JDlgAfbClientes(null, true);
       jDlgAfbClientes.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuAfbClientesActionPerformed

    private void jMnuAfbFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAfbFornecedoresActionPerformed
       JDlgAfbFornecedores jDlgAfbFornecedores = new JDlgAfbFornecedores(null, true);
       jDlgAfbFornecedores.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuAfbFornecedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmAfbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmAfbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmAfbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmAfbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmAfbPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMnuAfbClientes;
    private javax.swing.JMenuItem jMnuAfbFornecedores;
    private javax.swing.JMenuItem jMnuAfbProdutos;
    private javax.swing.JMenuItem jMnuAfbSair;
    private javax.swing.JMenuItem jMnuAfbUsuario;
    private javax.swing.JMenuItem jMnuAfbVendedores;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
